document.write("<header> Header </header>")
document.write("<div class='coco'><div class='container'><nav> Navigation </nav></div>")
document.write("<div class='container2' ><article> Article </article>")
document.write("<article> Article </article>")
document.write("<article> Article </article></div></div>")
document.write("<footer> Footer </footer>")